name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка SSH
      - name: Set up SSH key
        run: |
          echo "${{ secrets.DEPLOY_KEY_FRONTEND }}" > private_key.pem
          chmod 600 private_key.pem
          eval $(ssh-agent -s)
          ssh-add private_key.pem
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H 90.156.156.29 >> ~/.ssh/known_hosts
        env:
          DEPLOY_KEY_FRONTEND: ${{ secrets.DEPLOY_KEY_FRONTEND }}

      # Шаг 3: Выполнение скрипта деплоя фронтенда
      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no root@90.156.156.29 'bash /var/www/life-game/deploy-frontend.sh'
