name: Deploy Frontend

on:
  push:
    branches:
      - master  # Замените на вашу основную ветку, если отличается

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_FRONTEND }}

      # Шаг 3: Выполнение скрипта деплоя фронтенда
      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no root@90.156.156.29 'bash /var/www/life-game/deploy-frontend.sh'
